### ISSUE TITLE
Ошибка загрузчика (limine.sys size incorrect)

### ISSUE THREAD

**Issue by SergeyMC9730** [0Nera/SynapseOS#130]
**Описание**
Найдена ошибка не даёт загрузчику Limine **пройти дальше второй стадии.**

**Воспроизведение**
Шаги воспроизведения ошибки:
1. Скачать требуемые библиотеки *(`scripts/install.py` отсутствует по какой-то причине, поэтому я вручную всё скачал)*
2. Положить `limine-cd.bin` и `limine-cd-efi.bin` в папку `isodir`
3. Скомпилировать и запустить систему
4. Увидеть ошибку

**Ожидаемое поведение**
Система загрузится в терминал и им можно будет пользоваться

**Скриншоты**
![image](https://user-images.githubusercontent.com/57207009/220893293-53b3a5a5-bc31-4d53-ae80-d4de54460bc5.png)

**Среда:**
 - Железо(Эмулятор): **Qemu 6.2.0**
 - Время работы ОС: **0.3 сек**
 - Версия ядра: **[latest-unstable](https://github.com/0Nera/SynapseOS/releases/tag/latest-unstable)**

**Дополнительная информация**
```bash
dog@dog:~/Source/SynapseOS$ file isodir/limine.sys 
isodir/limine.sys: data
dog@dog:~/Source/SynapseOS$ 
```

**Comment by 0Nera** [comment]
Исправлено в новой версии

**Comment by SergeyMC9730** [comment]
Лимин теперь грузится нормально, но вот сама система -- нет. Она зависает на:
```
[DEBUG][arch//x86/lowlevel/boot/multiboot.c:multiboot_main:50]bootloader_name: Limine 4.20230221.0
```

**Comment by 0Nera** [comment]
> Лимин теперь грузится нормально, но вот сама система -- нет. Она зависает на:
> 
> ```
> [DEBUG][arch//x86/lowlevel/boot/multiboot.c:multiboot_main:50]bootloader_name: Limine 4.20230221.0
> ```

Проблема сохранилась?

**Comment by SergeyMC9730** [comment]
сохранилась24.02.2023, 12:55, "Aren Elchinyn" ***@***.***>:

Лимин теперь грузится нормально, но вот сама система -- нет. Она зависает на:
[DEBUG][arch//x86/lowlevel/boot/multiboot.c:multiboot_main:50]bootloader_name: Limine 4.20230221.0


Проблема сохранилась?

**Comment by 0Nera** [comment]
> 

Попробуй удалить все файлы связанные с limine в папке isodir
