### ISSUE TITLE
Задания для новичков

### ISSUE THREAD

**Issue by 0Nera** [0Nera/SynapseOS#131]
- [ ] Paging
- [ ] Higher half
- [ ] Кириллица
- [ ] Поддержка TrueType шрифтов
- [ ] Двойная буфферизация
- [ ] Устранение ошибок в многозадачности
- [ ] Запуск процессов в ring1/ring2/ring3
- [ ] SMBIOS 
- [ ] Автосборка модулей
- [ ] Релокация ELF
- [ ] Syscalls(прерывания)
- [ ] Syscalls(syscall/sysenter)

**Comment by evyas** [comment]
Попробую помочь

**Comment by evyas** [comment]
Беру на себя SMBIOS
