### ISSUE TITLE
Стандартная библиотека

### ISSUE THREAD

**Issue by 0Nera** [0Nera/SynapseOS#32]
Стандартные

- [ ] assert.h
- [ ] complex.h
- [ ] ctype.h
- [ ] errno.h
- [ ] fenv.h
- [ ] float.h
- [ ] inttypes.h
- [x] iso646.h
- [ ] limits.h
- [ ] locale.h
- [x] math.h
- [ ] setjmp.h
- [ ] signal.h
- [ ] stdalign.h 
- [ ] stdarg.h
- [ ] stdatomic.h 
- [ ] stdbool.h 
- [ ] stddef.h
- [X] stdint.h
- [x] stdio.h
- [x] stdlib.h
- [x] stdnoreturn.h
- [x] string.h
- [ ] tgmath.h
- [ ] threads.h 
- [ ] time.h
- [ ] uchar.h
- [ ] wchar.h
- [ ] wctype.h

Только под SynapseOS

- [ ] module.h
- [ ] GUI.h
- [ ] graphic.h
- [x] sysapi.h
- [ ] neuro.h
- [ ] compiler.h
- [ ] filesystems.h
- [ ] crypto.h
- [ ] asm.h

**Comment by 0Nera** [comment]
module.h - создание и работы с модулями
 GUI.h - графический интерфейс ПО
 graphic.h - графика
 sysapi.h   - системные функции
 neuro.h - для работы с нейросетями
 compiler.h - для создания компиляторов
 filesystems.h - файловые системы
 crypto.h - шифрование
 asm.h - макросы для работы с ассемблером

**Comment by NDRAEY** [comment]
stdio.h
stdlib.h
string.h
уже есть

**Comment by pimnik98** [comment]
stdio.h math.h - имеется, но не доработано
sysapi.h - системные функции, имеется но заменено на system.h

**Comment by NDRAEY** [comment]
stdbool.h
ctypes.h -> apps/libc
