### ISSUE TITLE
Языки программирования

### ISSUE THREAD

**Issue by 0Nera** [0Nera/SynapseOS#6]
- [x] C/C++/GAS
- [ ] BASIC
- [ ] Python
- [ ] Fasm
- [ ] Node.js
- [ ] Go
- [ ] Java
- [ ] Lua

**Comment by noverd** [comment]
Нужно в первую очередь перенести C and FASM

**Comment by 0Nera** [comment]
> Нужно в первую очередь перенести C and FASM

Для начала надо реализовать все API требуемое для Newlib

**Comment by NDRAEY** [comment]
Привет, я могу портировать Lua

**Comment by 0Nera** [comment]
> Привет, я могу портировать Lua

Буду рад принять pull request с Lua

**Comment by Domaman202** [comment]
Го pascal?

**Comment by 0Nera** [comment]
> Го pascal?

А кто им займется когда столько задач на ядро?

**Comment by Domaman202** [comment]
я
