### ISSUE TITLE
Не отображается введённый в консоли текст

### ISSUE THREAD

**Issue by Domaman202** [0Nera/SynapseOS#61]
**Описание**
Не отображается введённый в консоли текст, в логах присутствует ошибка линковки: `ld.lld: error: cannot open ./bin/asm.o: No such file or directory`

**Воспроизведение**
1. Скачать репозиторий
3. Собрать систему командой python3 build.py

**Ожидаемое поведение**
Что вы ожидали увидеть?

**Скриншоты**
![image](https://user-images.githubusercontent.com/51743763/180743834-711cb590-5e73-4f9e-a661-72237944f260.png)

**Среда:**
 - os: Garuda Linux x86_64 
 - qemu: 7.0.0
 - lld: 14.0.6
 - clang: `14.0.6`
`Target: x86_64-pc-linux-gnu`
`Thread model: posix`

[Qemu.log](https://github.com/0Nera/SynapseOS/files/9179868/Qemu.log)

**Comment by 0Nera** [comment]
Программы на fasm введены в тулчейн, установите компилятор fasm для того чтобы убрать предупреждение. 

Проблема с вводом возникла из-за TUI, в кратчайшие сроки исправим

**Comment by pimnik98** [comment]
Для ручного исправления, перед shell() в kernel.c добавить
`changeStageKeyboard(1);`
Это разблокирует ввод с клавиатуры

**Comment by Domaman202** [comment]
Интересное замечание, ввод работает, а вот вывод введённого символа нет ^^
