### ISSUE TITLE
Не стартует ОС в VMWare Workstation 12

### ISSUE THREAD

**Issue by pimnik98** [0Nera/SynapseOS#65]
При старте ядра, успевает обработать информацию о оперативной памяти.
Пишет установлено: 167892 KB -> 163 MB
А доступно: 36414 KB -> 35 MB
В виртуальной машине установлено значение в 36 MB

После определения режима ОЗУ, выскакивает ошибка виртуальной машины и гласит оно следующие:
`Произошел сбой виртуального процессора что вызвало выключение. Если эта ошибка произошла за пределами виртуальной машины, это вызвало бы физическую машину для перезагрузки. Выключение может быть вызвано неправильной настройкой виртуальной машины, ошибка в гостевой системе, или проблема в VMware Workstation.`

Хост: 
OS: Windows 8.1 x64
RAM: 4 GB DDR2

Виртуалка:
OS: SynapseOS v0.2.12 (Dev) (unstable)
RAM: 36 MB
CPU: 1 Core
HDD: 8 GB

**Comment by 0Nera** [comment]
Как и следовало ожидать. Наш убогий менеджмент памяти ломается на разном железе, в том числе и на виртуальном

**Comment by pimnik98** [comment]
Требуется исправить PCi.c для решения данной проблемы
