### ISSUE TITLE
Программы

### ISSUE THREAD

**Issue by 0Nera** [0Nera/SynapseOS#7]
- [ ] i686-elf-tools
- [ ] Nano
- [ ] wget
- [ ] git

**Comment by noverd** [comment]
Могу перенести нано

**Comment by noverd** [comment]
Точнее его клон

**Comment by 0Nera** [comment]
> Точнее его клон

Неплохо, только учти: Api для работы с файлами отсутствует

**Comment by noverd** [comment]
А каким способ тогда с файловой системой работать?

**Comment by noverd** [comment]
Хотя в SSFS.c есть немного Апи

**Comment by 0Nera** [comment]
> Хотя в SSFS.c есть немного Апи

Скоро Ex2 займусь

**Comment by noverd** [comment]
Отлично
