### ISSUE TITLE
Не запускается.

### ISSUE THREAD

**Issue by Domaman202** [0Nera/SynapseOS#72]
**Описание**
Сбой при запуске.

**Воспроизведение**
Шаги воспроизведения ошибки:
1. Скачать репозиторий
2. Собрать систему командой `python3 build.py`

**Ожидаемое поведение**
Работа как 2 дня назад.

**Скриншоты**
![image](https://user-images.githubusercontent.com/51743763/181189527-b2d1274d-03f3-4e62-bc88-cdd5e880c780.png)

**Среда:**
 - os: Garuda Linux x86_64 
 - qemu: 7.0.0
 - lld: 14.0.6
 - clang: `14.0.6`
`Target: x86_64-pc-linux-gnu`
`Thread model: posix`

[Qemu.log](https://github.com/0Nera/SynapseOS/files/9196133/Qemu.log)

**Comment by 0Nera** [comment]
Отключи инициализацию экспериментального драйвера floppy в kernel.c
