### ISSUE TITLE
Игры

### ISSUE THREAD

**Issue by 0Nera** [0Nera/SynapseOS#8]
- [ ] DOOM
- [x] KolibriRPG
- [x] Игры от alesson
- [x] Tetris
- [ ] Онлайн игра (беру на себя)
- [x] Сапер
- [X] Змейка

**Comment by Agzam4** [comment]
Свои варианты можно предлагать? На каком языке должны быть эти игры? Какие ограничения для них?

**Comment by 0Nera** [comment]
@Agzam4  свои игры можно писать. Рекомендуется писать на C/C++/GAS
