### ISSUE TITLE
Ошибка #PF Page-Fault

### ISSUE THREAD

**Issue by noverd** [0Nera/SynapseOS#84]
![Снимок экрана от 2022-08-07 09-12-27](https://user-images.githubusercontent.com/71782778/183277989-f9c7dcf1-ce6a-4a0f-ac82-11ee2ff1987a.png)
Qemu Ubuntu

**Comment by noverd** [comment]
Как это всё таки пофиксить?

**Comment by pimnik98** [comment]
Отключи в kernel.c -> инициализацию PCI
Только после этого стартует.

Опционально:
также я отключил ata_init
RTL8139_init
vfs_mount

**Comment by pimnik98** [comment]
https://github.com/0Nera/SynapseOS/issues/79

**Comment by noverd** [comment]
Окей, попробую

**Comment by noverd** [comment]
Не помогло

**Comment by noverd** [comment]
Дорогие товарищи, тут ошибка с компиляцией в бубнте. Я не смог её решить, лучше просите других вам компилить
